name: Deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
        with:
          persist-credentials: false
      - uses: nais/docker-build-push@3b44f7c419b9511ad7c8b72174b3cc078d570bed
        id: docker-push-neo4j
        with:
          team: appsec
          dockerfile: Dockerfile.neo4j
          image_suffix: neo4j
      - uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/neo4j.yaml
          IMAGE: ${{ steps.docker-push-neo4j.outputs.image }}
      - uses: nais/docker-build-push@3b44f7c419b9511ad7c8b72174b3cc078d570bed
        id: docker-push-cartography
        with:
          team: appsec
          dockerfile: Dockerfile.cartography
      - uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/cartography.yaml
          IMAGE: ${{ steps.docker-push-cartography.outputs.image }}
